### PR TITLE
Fix sum(::AbstractArray{<:AbstractMutable}; dims)

### LINKED ISSUE #309: sum with init and dims
I can't pin-point when this stop working, but this is probably a breaking accidental change:
MathOptInterface v1.31.2
MA 1.5.1

```julia
julia> import MathOptInterface as MOI

julia> X = reshape(MOI.VariableIndex.(1:12), 3, 4)

julia> sum(X; init=0.0, dims=1)
ERROR: MethodError: no method matching operate(::typeof(sum), ::Matrix{MathOptInterface.VariableIndex}; init::Float64, dims::Int64)
This error has been manually thrown, explicitly, so the method may exist but be intentionally marked as unimplemented.

Closest candidates are:
  operate(::typeof(sum), ::AbstractArray; init) got unsupported keyword argument "dims"
   @ MutableArithmetics ~/.julia/packages/MutableArithmetics/6jxVC/src/reduce.jl:53
  operate(::typeof(-), ::Any) got unsupported keyword arguments "init", "dims"
   @ MutableArithmetics ~/.julia/packages/MutableArithmetics/6jxVC/src/interface.jl:191
  operate(::typeof(one), ::Any) got unsupported keyword arguments "init", "dims"
   @ MutableArithmetics ~/.julia/packages/MutableArithmetics/6jxVC/src/interface.jl:238
  ...

Stacktrace:
 [1] kwerr(::@NamedTuple{init::Float64, dims::Int64}, ::Function, ::Function, ::Matrix{MathOptInterface.VariableIndex})
   @ Base ./error.jl:165
 [2] sum(a::Matrix{MathOptInterface.VariableIndex}; kwargs::@Kwargs{init::Float64, dims::Int64})
   @ MutableArithmetics ~/.julia/packages/MutableArithmetics/6jxVC/src/dispatch.jl:17
 [3] top-level scope
   @ REPL[8]:1
```

### PR DESCRIPTION
**Pull request by odow**
Closes #309

### CODE REVIEW

**Comment by blegat** [comment]
Any reason you used `missing` instead of `:`

File: src/dispatch.jl [hunk 1]
```diff
@@ -13,8 +13,18 @@
...
 abstract type AbstractMutable end
 
-function Base.sum(a::AbstractArray{<:AbstractMutable}; kwargs...)
-    return operate(sum, a; kwargs...)
+function Base.sum(
+    a::AbstractArray{T};
+    dims = :,
+    init = zero(promote_operation(+, T, T)),
+) where {T<:AbstractMutable}
+    if !ismissing(dims)
```
Comment (odow) [inline src/dispatch.jl:21]:
```suggestion
    if dims !== :
```
