### PR TITLE
Fix implementation of fused_map_reduce

### LINKED ISSUE #92: Fix dot for Array of Arrays

### PR DESCRIPTION
**Pull request by odow**
Closes #92

This results in a few more allocations, but it fixes incorrect behavior.

In particular, `master` currently produces:

```julia
julia> x = [5.0, 6.0]
2-element Vector{Float64}:
 5.0
 6.0

julia> y = Vector{Union{Float64,String}}(x)
2-element Vector{Union{Float64, String}}:
 5.0
 6.0

julia> MA.operate(*, x', y)
ERROR: MethodError: no method matching zero(::Type{Union{Float64, String}})
Closest candidates are:
  zero(::Union{Type{P}, P}) where P<:Dates.Period at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Dates/src/periods.jl:53
  zero(::JuMP.GenericQuadExpr) at /Users/oscar/.julia/packages/JuMP/Z1pVn/src/quad_expr.jl:109
  zero(::JuMP.GenericAffExpr) at /Users/oscar/.julia/packages/JuMP/Z1pVn/src/aff_expr.jl:192
  ...
Stacktrace:
  [1] _instantiate_zero(#unused#::Type{Union{Float64, String}})
    @ MutableArithmetics ~/.julia/packages/MutableArithmetics/maUDe/src/interface.jl:28
  [2] promote_operation_fallback(op::typeof(*), #unused#::Type{Float64}, #unused#::Type{Union{Float64, String}})
    @ MutableArithmetics ~/.julia/packages/MutableArithmetics/maUDe/src/interface.jl:51
  [3] promote_operation(::typeof(*), ::Type, ::Type)
    @ MutableArithmetics ~/.julia/packages/MutableArithmetics/maUDe/src/interface.jl:113
  [4] promote_operation_fallback(#unused#::typeof(LinearAlgebra.dot), #unused#::Type{Float64}, #unused#::Type{Union{Float64, String}})
    @ MutableArithmetics ~/.julia/packages/MutableArithmetics/maUDe/src/interface.jl:666
  [5] promote_operation(::typeof(LinearAlgebra.dot), ::Type, ::Type)
    @ MutableArithmetics ~/.julia/packages/MutableArithmetics/maUDe/src/interface.jl:113
  [6] promote_map_reduce(::Function, ::Type, ::Type)
    @ MutableArithmetics ~/.julia/packages/MutableArithmetics/maUDe/src/reduce.jl:32
  [7] fused_map_reduce(::typeof(MutableArithmetics.add_dot), ::Vector{Float64}, ::Vector{Union{Float64, String}})
    @ MutableArithmetics ~/.julia/packages/MutableArithmetics/maUDe/src/reduce.jl:41
  [8] operate(#unused#::typeof(LinearAlgebra.dot), x::Vector{Float64}, y::Vector{Union{Float64, String}})
    @ MutableArithmetics ~/.julia/packages/MutableArithmetics/maUDe/src/implementations/LinearAlgebra.jl:486
  [9] operate(#unused#::typeof(*), x::LinearAlgebra.Adjoint{Float64, Vector{Float64}}, y::Vector{Union{Float64, String}})
    @ MutableArithmetics ~/.julia/packages/MutableArithmetics/maUDe/src/implementations/LinearAlgebra.jl:459
 [10] top-level scope
    @ REPL[141]:1

julia> z = [x, x]
2-element Vector{Vector{Float64}}:
 [5.0, 6.0]
 [5.0, 6.0]

julia> MA.operate(LinearAlgebra.dot, z, z)
ERROR: MethodError: promote_operation_fallback(::typeof(LinearAlgebra.dot), ::Type{Vector{Float64}}, ::Type{Vector{Float64}}) is ambiguous. Candidates:
  promote_operation_fallback(op::Function, x::Type{var"#s1"} where var"#s1"<:AbstractArray, y::Type{var"#s2"} where var"#s2"<:AbstractArray) in MutableArithmetics at /Users/oscar/.julia/packages/MutableArithmetics/maUDe/src/interface.jl:15
  promote_operation_fallback(::typeof(LinearAlgebra.dot), ::Type{A}, ::Type{B}) where {A, B} in MutableArithmetics at /Users/oscar/.julia/packages/MutableArithmetics/maUDe/src/interface.jl:661
Possible fix, define
  promote_operation_fallback(::typeof(LinearAlgebra.dot), ::Type{A}, ::Type{B}) where {A<:AbstractArray, B<:AbstractArray}
Stacktrace:
 [1] promote_operation(::typeof(LinearAlgebra.dot), ::Type, ::Type)
   @ MutableArithmetics ~/.julia/packages/MutableArithmetics/maUDe/src/interface.jl:113
 [2] promote_map_reduce(::Function, ::Type, ::Type)
   @ MutableArithmetics ~/.julia/packages/MutableArithmetics/maUDe/src/reduce.jl:32
 [3] fused_map_reduce(::typeof(MutableArithmetics.add_dot), ::Vector{Vector{Float64}}, ::Vector{Vector{Float64}})
   @ MutableArithmetics ~/.julia/packages/MutableArithmetics/maUDe/src/reduce.jl:41
 [4] operate(#unused#::typeof(LinearAlgebra.dot), x::Vector{Vector{Float64}}, y::Vector{Vector{Float64}})
   @ MutableArithmetics ~/.julia/packages/MutableArithmetics/maUDe/src/implementations/LinearAlgebra.jl:486
 [5] top-level scope
   @ REPL[143]:1
```

### CODE REVIEW

File: src/reduce.jl [hunk 1]
```diff
@@ -22,24 +22,32 @@ reduce_op(op::AddSubMul) = add_sub_op(op)
...
+        push!(expr.args, :(zero(f(args[$i]))))
+    end
+    return expr
 end
 
 function fused_map_reduce(op::F, args::Vararg{Any,N}) where {F<:Function,N}
     _check_same_length(args...)
-    T = promote_map_reduce(op, eltype.(args)...)
-    accumulator = neutral_element(reduce_op(op), T)
+    if length(args[1]) == 0
```
Comment (blegat) [inline src/reduce.jl:40]:
```suggestion
    if isempty(args[1])
```

**Comment by blegat** [comment]
Can't we just implement `promote_operation(::typeof(*), ::Type{Array...}, ::Type{Array...})` ? `_accumulator` is another solution but it's quite orthogonal to the way the rest of MA works.

**Comment by odow** [comment]
Promote doesn't handle the case of `Vector{Union{String,Float64}}` containing only `Float64`. `LinearAlgebra.dot` and `Base.:*` both work fine, because they deal with the element data at runtime, rather than looking at the container type.

For better or worse, `Vector{Union{String,Float64}}` shows up in the JuMP documentation, so not handling this case properly is a breaking change. 

The current MA works around it by first calling `MA.operate!!(MA.add_mul, MA.Zero(), arg)` on every argument in `*(args...)`. That causes additional copies, and I think was just added to work-around this particular case.

File: src/reduce.jl [hunk 2]
```diff
@@ -22,24 +22,32 @@ reduce_op(op::AddSubMul) = add_sub_op(op)
...
+    expr = Expr(:call, :(map_op(op)))
+    for i in 1:N
+        push!(expr.args, :(zero(f(args[$i]))))
+    end
+    return expr
 end
 
 function fused_map_reduce(op::F, args::Vararg{Any,N}) where {F<:Function,N}
     _check_same_length(args...)
-    T = promote_map_reduce(op, eltype.(args)...)
```
Comment (blegat) [inline src/reduce.jl:41]: What about `T = promote_map_reduce(op, _concrete_eltype.(args)...)` where `_concrete_eltype` checks for the first elements etc... ? At least this gives a function that we can easily reuse in the rest of MA to have something consistent.
Also, we then just have to add a `promote_operation` method for arrays

Comment (odow) [reply src/reduce.jl:41]: Updated to use your suggestion.

**Review by blegat — APPROVED** [review]
